name: Render Animation

on:
  schedule:
    - cron: '0 */6 * * *' # cada 6 horas
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Generar el GitHub Snake
      - name: Render github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: kerizrh  # <-- tu usuario de GitHub
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg

      # 3. Subir los archivos generados a la rama 'output'
      - name: Commit github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Update GitHub Snake"
          keep_files: true
