name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *" # Ejecuta cada día a medianoche
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # 1. Clona el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Genera las estadísticas con GitHub Readme Stats
      - name: Generate GitHub Stats
        run: |
          curl -o dist/github-stats.svg "https://github-readme-stats.vercel.app/api?username=${{ github.repository_owner }}&theme=algolia&show_icons=true"
          curl -o dist/github-streak.svg "https://streak-stats.demolab.com?user=${{ github.repository_owner }}&theme=algolia"

      # 3. Publica los archivos generados en la rama output
      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
          allow_empty_commit: true
          commit_message: "Update GitHub Stats"

